travis:
  secure:
    BINSTAR_TOKEN: TXOweBdeKvI3NKZvxHp5FqSMaolqj5QY6ZaWL4+/JBAK4UkP6gR7MZPh9Uuv63YJiczQX0I51TmNcAkCLpZ6vzj8qlAYTjj3Fip1Sif+4HeRUv9Iwgxlcf6lNlT8yVRXkErrddKh7yumPBkYccdX5U7voYJuzfacg2NDk6MWIDlyLdvTDGNcSGo/3lklqR9czoRhIu/XiMi18nMomnEHDpLIBB9aeEKN3iXhX04tunrd+3xIJAUl3RjrDpL6SzYPESr+maLV2Rb3S5j9OS7nzeshCdMp+v5D6YtnFAd7RJRJW5av+CoRzIkYpNL7zFGsieOVFJb/6JlEoSVJ9a/xYUSjm4I+qDDJr4MIt/uO1hAei6k+AYDL5U85DI0uwlZ+wOTDriEN4b/cGf12sterLfF6qqZJlk55lJ6JCiboAvqyU3tSeh3m4CWCZEikgmkF8lLD/SJq0KJGgr9kQoRbgfKIyGx6faddv/eUga46aMVya9s+e06jmsgjpmsJGsi62NdAItoowdY2481PxNbKGmmGZUKDlN/vatkWUZUXwY40mdzmQDBYbBDmU8vYEahA2Xb6pQai9PasqgkSPBS5sSEvQrjmiDvVg8ml6XrNc4kBRmEroeOkTNtMqpPTYSkg7XZZGM5ZMKKPmMVg9r1MwDNDFuZrwHS4fd9p1Ik8uHU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
