travis:
  secure:
    BINSTAR_TOKEN: oNpp6k/Ok9gFCwG9QFtIfA+NgU3SRk5vFRRmHkS0bEdViQ1Fupprv5Y59yovTwuzklyYxXzBKzP3qdWGzcbUFrFgs1k7KGPC/o0BjzKbZDbPzaSBfoP8GPFLtYW45piJ8G0+e2hFkgH6P7rcqacVhBSzzus0ELFMNAFvBfwFG05TCWkKfCuUrjB2+fOFDwY5X8c8xiekvf2Nt/W7Jsji0s4kDE3wyVIBN7onXcGZu4G8KzM0sSXalrL/Z8PAk5VoA8PJmk0b4BWbWmz+uGg+RBDWZed/OKg/ew+z/yQE81Bd/AIqtkujPxdzfkmIh+spW7aadcXQ/omFfgGPd8jR+7gEokJoXH6y4InpPanuPttadu/FBlcxe6LXz2DIj/ipgB6+apXUTaChte5DK+0Yv92qymkU+cqJlmCGhh/JgzgnYoj68tCzI6H7W8MIO4N7oVlsZuROrouOvsj/gbg+ipPHyrenT3Bahq5I+q07RTVWk3Ptt1yolyR77PZpHfwakbiF/IVnirrr2ftCPSdfS9wlQFGGpHBLkStjKcx47emRR7matMwGbLthM2wgOfkef9HAytl+cvNqL28YlY+qP3T0GnxHgbfjOlk2cAgsexsrMl61Kxt6hUmzYG//fYsU1IXSM7P4Mijf+mmV6S+SC+iwXVIICU0+ioPV+zyV72A=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
